export const T = {
    ES: {
        BUTTON: 'EN',
        WELCOME: '¡Bienvenido/a a nuestro sitio!',
        COMPLETE: 'Complete este campo con su ',
        TITLE: 'Crea tu cuenta',
        NAME: 'Nombre',
        PLACEHOLDER_NAME: 'Ingrese aquí su Nombre',
        LAST_NAME: 'Apellido',
        PLACEHOLDER_LAST_NAME: 'Ingrese aquí su Apellido',
        PHONE_NUMBER: 'Teléfono',
        PLACEHOLDER_PHONE_NUMBER: 'Ingrese aquí su Teléfono',
        EMAIL: 'Correo',
        PLACEHOLDER_EMAIL: 'Ingrese aquí su Correo',
        PASSWORD: 'Contraseña',
        PLACEHOLDER_PASSWORD: 'Ingrese aquí su contraseña',
        CONFIRM_PASSWORD: 'Confirma la contraseña',
        PLACEHOLDER_CONFIRM_PASSWORD: 'Vuelva a ingresar aquí su contraseña',
        BUTTON_SIGN_UP: 'Crea tu cuenta',
        ALERT: '¡Usuario Creado!',
        MINLENGTH: '. Y revise el valor mínimo de caracteres que es de ',
        REQUIRED: 'Complete este campo con su ',
        MAX_LENGTH_TEXT: 'El valor ingresado debe ser menor a 20 caracteres.',
    },

    EN: {
        BUTTON: 'ES',
        WELCOME: 'Welcome to our website!',
        COMPLETE: 'Fill in this field with your ',
        TITLE: 'Create your account',
        NAME: 'First Name',
        LAST_NAME: 'Last name',
        PHONE_NUMBER: 'Phone number',
        EMAIL: 'Email',
        PASSWORD: 'Password',
        CONFIRM_PASSWORD: 'Confirm password',
        BUTTON_SIGN_UP: 'Create your account',
        ALERT: 'User Created!',
        PLACEHOLDER_NAME:'Enter your First Name here',
        PLACEHOLDER_LAST_NAME:'Enter your Last name here',
        PLACEHOLDER_PHONE_NUMBER:'Enter your Phone number here',
        PLACEHOLDER_EMAIL:'Enter your Email here',
        PLACEHOLDER_PASSWORD:'Enter your Password here',
        PLACEHOLDER_CONFIRM_PASSWORD:'Enter your Password here again',
        REQUIRED: 'This is required',
        MAX_LENGTH_TEXT: 'The value entered must be less than 20 characters.',
    }
};

